export const imagePaths = {
  avatar01: "/images/home/avatar.png",
  home: "/images/home/home.svg",
  home01: "/images/home/home_1.svg",
  patient: "/images/home/user-group.svg",
  patient01: "/images/home/user-group-1.svg",
  history: "/images/home/document-clipped.svg",
  history01: "/images/home/document-clipped-1.svg",
  settings: "/images/home/gearring.svg",
  settings01: "/images/home/gearring-1.svg",
  right: "/images/home/circle-right.svg",
  loading: "/images/home/loading.gif",
  chicken: "/images/assessment/chicken.png",
  horse: "/images/assessment/horse.png",
  dog: "/images/assessment/dog.png",
};
